version: '3.8'

services:
  frontend:
    container_name: react-app
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - '3000:3000'
    networks:
        - app-network
    restart: always
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: brain-stormer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db: