server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brain-stormer
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true